apiVersion: v2
name: kubevirt-redfish
description: A Helm chart that provides a Redfish API server for KubeVirt VMs
type: application
version: 0.2.2-system-id-convention
appVersion: "v0.2.1-67-gfee285c"
keywords:
  - kubevirt
  - redfish
  - virtualization
  - api
home: https://github.com/kubevirt/redfish-controller
sources:
  - https://github.com/kubevirt/redfish-controller
maintainers:
  - name: Brandon B. Jozsa
    email: bjozsa@redhat.com
icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png